// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7X_piWkweDRqT83Bx8uiAgSh-TVZS1cs',
    appId: '1:985002247624:web:1ef85d3a530da4db6decfd',
    messagingSenderId: '985002247624',
    projectId: 'checkplay-5e169',
    authDomain: 'checkplay-5e169.firebaseapp.com',
    storageBucket: 'checkplay-5e169.firebasestorage.app',
    measurementId: 'G-3NV03D148V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyB20ZQe_7ULy5ms_pV6Yk0VMtNxDJYGA',
    appId: '1:985002247624:android:2730789d620bf8dd6decfd',
    messagingSenderId: '985002247624',
    projectId: 'checkplay-5e169',
    storageBucket: 'checkplay-5e169.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rx_HEAT_ZxK8TEfKcnAXyW55EWPT79s',
    appId: '1:985002247624:ios:bfe20a74a9f826cb6decfd',
    messagingSenderId: '985002247624',
    projectId: 'checkplay-5e169',
    storageBucket: 'checkplay-5e169.firebasestorage.app',
    iosBundleId: 'br.com.hksntech.checkplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4rx_HEAT_ZxK8TEfKcnAXyW55EWPT79s',
    appId: '1:985002247624:ios:10548874033ac3116decfd',
    messagingSenderId: '985002247624',
    projectId: 'checkplay-5e169',
    storageBucket: 'checkplay-5e169.firebasestorage.app',
    iosBundleId: 'com.example.checkplayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7X_piWkweDRqT83Bx8uiAgSh-TVZS1cs',
    appId: '1:985002247624:web:2d9eb17556b072226decfd',
    messagingSenderId: '985002247624',
    projectId: 'checkplay-5e169',
    authDomain: 'checkplay-5e169.firebaseapp.com',
    storageBucket: 'checkplay-5e169.firebasestorage.app',
    measurementId: 'G-LY1WQP5M5Q',
  );

}