// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmIxC9SOzgTYHedsUSVNJs1Pv1uHCn8k',
    appId: '1:145030948040:web:b2e2ef0d3741ea307f31fd',
    messagingSenderId: '145030948040',
    projectId: 'checkplay-5afca',
    authDomain: 'checkplay-5afca.firebaseapp.com',
    storageBucket: 'checkplay-5afca.firebasestorage.app',
    measurementId: 'G-D2CLM225EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaT58GL4NAkW89CHd7upAe6G8lAaEzAOk',
    appId: '1:145030948040:android:513e87873aa9436b7f31fd',
    messagingSenderId: '145030948040',
    projectId: 'checkplay-5afca',
    storageBucket: 'checkplay-5afca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL8aI4xsZeMXtMHpbHF3lPTzjYRip96Pw',
    appId: '1:145030948040:ios:154f4518ceff674e7f31fd',
    messagingSenderId: '145030948040',
    projectId: 'checkplay-5afca',
    storageBucket: 'checkplay-5afca.firebasestorage.app',
    iosBundleId: 'com.example.checkplayMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL8aI4xsZeMXtMHpbHF3lPTzjYRip96Pw',
    appId: '1:145030948040:ios:154f4518ceff674e7f31fd',
    messagingSenderId: '145030948040',
    projectId: 'checkplay-5afca',
    storageBucket: 'checkplay-5afca.firebasestorage.app',
    iosBundleId: 'com.example.checkplayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGmIxC9SOzgTYHedsUSVNJs1Pv1uHCn8k',
    appId: '1:145030948040:web:f555de9ce81dd4567f31fd',
    messagingSenderId: '145030948040',
    projectId: 'checkplay-5afca',
    authDomain: 'checkplay-5afca.firebaseapp.com',
    storageBucket: 'checkplay-5afca.firebasestorage.app',
    measurementId: 'G-08KLB0Z0P6',
  );
}
